server:
  port: 8443

spring:
  datasource:
    username: root
    password: JancerWu
    url: jdbc:mysql://127.0.0.1:3306/white_jotter?useUnicode=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
